<ActionsScreen@MDScreen>:
    name: "Actions"

    MDBoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "Actions"
            left_action_items: [["menu", lambda x: app.root.get_screen("maininfo").ids.nav_drawer.set_state("open")]]
            right_action_items: [["close", lambda x: app.root.get_screen("maininfo").close()]]

        MDBoxLayout:
            orientation: "vertical"
            spacing: "8dp"
            padding: "8dp"